Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop_thien_thanh.Models;
using Microsoft.AspNet.Identity;
namespace Shop_thien_thanh.Controllers
{
    public class KhachHangController : Controller
    {
        FASHIONMODELDataContext db = new FASHIONMODELDataContext();
        // GET: TaiKhoan
        public ActionResult DangKy(string message)
        {
            ViewBag.Message = message;
            return View();
        }

        // Cách 1
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult DangKy(FormCollection frm)
        //{
        //    KhachHang khachHangMoi = new KhachHang();

        //    if (frm["NhapLaiMatKhau"] != frm["MatKhau"])
        //    {
        //        ModelState.AddModelError("", "Nhập lại mật khẩu không khớp.");
        //        return View(frm);
        //    }
        //    if(frm["TenDangNhap"] == "")
        //    {
        //        ModelState.AddModelError("", "Bạn chưa nhập tên đăng nhập.");
        //        return View(frm);
        //    }
        //    if (frm["MatKhau"] == "")
        //    {
        //        ModelState.AddModelError("", "Bạn chưa nhập mật khẩu.");
        //        return View(frm);
        //    }
        //    if(frm["HoTen"] == "")
        //    {
        //        if (frm["HoTen"] == "")
        //        {
        //            ModelState.AddModelError("", "Bạn chưa nhập họ tên.");
        //            return View(frm);
        //        }
        //    }
        //    khachHangMoi.HoTen = frm["HoTen"];
        //    khachHangMoi.MatKhau = frm["MatKhau"];
        //    khachHangMoi.TenDangNhap = frm["TenDangNhap"];
        //    khachHangMoi.NgaySinh = DateTime.Parse(frm["NgaySinh"]);
        //    if(bool.Parse(frm["GioiTinh"]) == true)
        //    {
        //        khachHangMoi.GioiTinh = true;
        //    }
        //    else
        //    {
        //        khachHangMoi.GioiTinh = false;
        //    }
        //    khachHangMoi.Email = frm["Email"];
        //    khachHangMoi.DienThoai = frm["DienThoai"];

        //    db.KhachHangs.InsertOnSubmit(khachHangMoi);
        //    db.SubmitChanges();
        //    return RedirectToAction("DangKy", new { message = "Đăng ký thành công." });
        //}

        // Cách 2
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy(KhachHang khachHangMoi, string NhapLaiMatKhau)
        {
            if(db.KhachHangs.FirstOrDefault(m=>m.TenDangNhap == khachHangMoi.TenDangNhap) != null)
            {
                ModelState.AddModelError("loitendangnhap", "Tên đăng nhập đã tồn tại.");

            }
            if (NhapLaiMatKhau != khachHangMoi.MatKhau)
            {
                ModelState.AddModelError("", "Nhập lại mật khẩu không khớp.");
            }
            
            if (ModelState.IsValid == false)
            {
                return View(khachHangMoi);
            }
            else
            {


                db.KhachHangs.InsertOnSubmit(khachHangMoi);
                db.SubmitChanges();
                return RedirectToAction("DangKyThanhCong");
            }
        }

        public ViewResult DangKyThanhCong()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangNhap(KhachHang kh)
        {
            KhachHang khachhangDangNhap = db.KhachHangs.FirstOrDefault(m => m.TenDangNhap == kh.TenDangNhap && m.MatKhau == kh.MatKhau);
            if (khachhangDangNhap != null)
            {
                // Đăng nhập thành công
                // Tạo ra 2 biến Session có name là tendangnhap, hoten 
                Session["tendangnhap"] = kh.TenDangNhap;
                Session["hoten"] = khachhangDangNhap.HoTen;
                Session["phanquyen"] = khachhangDangNhap.PhanQuyen;
                if (khachhangDangNhap.PhanQuyen == "Admin")
                {
                    
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else
                {

                    return Content("<script>  window.location.replace('" + Url.Action("Index", "Home") + "'); </script>");

                }
            }
            else
            {
                return Content("<script> alert('Sai tài khoản hoặc mật khẩu');  window.location.replace('" + Url.Action("Index", "Home") + "'); </script>");
            }
        }

        public ActionResult DangXuat()
        {
            Session["tendangnhap"] = null;
            Session["hoten"] = null;
            Session["phanquyen"] = null;
            return RedirectToAction("Index", "Home", new { area=""});
        }
            
    }
}

Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop_thien_thanh.Models;
using PagedList.Mvc;
using PagedList;
namespace Shop_thien_thanh.Controllers
{
    public class SanPhamController : Controller
    {
        FASHIONMODELDataContext data = new FASHIONMODELDataContext();
        // GET: SanPham
        
        public ActionResult LocTheoLoai(int phanloaiID, int? page)
        {
            PhanLoai phanLoai = (from pl in data.PhanLoais where pl.PhanLoaiID == phanloaiID select pl).FirstOrDefault();
            if(phanLoai == null)
            {
                return HttpNotFound();
            }
            ViewBag.TenPhanLoai = phanLoai.TenPhanLoai;
            List<SanPham> model = (from sp in data.SanPhams where phanLoai.Nhomsps.Contains(sp.Nhomsp) orderby  sp.SanPhamID descending  select sp).ToList();

            return View(model.ToPagedList(page ?? 1, 8));
        }

        public ActionResult LocTheoNhom(int nhomspID, int? page)
        {
            Nhomsp nhomSP = (from nsp in data.Nhomsps where nsp.NhomspID == nhomspID select nsp).FirstOrDefault();
            if(nhomSP == null)
            {
                return HttpNotFound();
            }
            ViewBag.TenNhom = nhomSP.TenNhomsp;
            List<SanPham> model = (from sp in data.SanPhams where sp.NhomspID == nhomspID orderby sp.SanPhamID descending select sp).ToList();
            return View(model.ToPagedList(page ?? 1, 8));
        }


        public ActionResult ChiTiet(int id)
        {
            // Lọc sản phẩm theo tham số id

            // Cách 1: 
           // SanPham model = data.SanPhams.FirstOrDefault(m => m.SanPhamID == id);

            // Cách 2:
            SanPham model = (from sp in data.SanPhams where sp.SanPhamID == id select sp).FirstOrDefault();
            if(model == null)
            {
                return HttpNotFound();
            }
            ViewBag.sanPhamCungNhom = (from sp in data.SanPhams where sp.NhomspID == model.NhomspID && sp.SanPhamID != model.SanPhamID select sp).Take(8).ToList(); 
            return View(model);
        }
        public ActionResult TimKiem(string tukhoa)
        {
            List<SanPham> model = (from sp in data.SanPhams where sp.TenSanPham.Contains(tukhoa) select sp).ToList();
            ViewBag.TuKhoa = tukhoa;
            return View(model);
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>

    <link href="~/Content/Style/default.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.11.0.min.js"></script>
    <script src="~/Scripts/Thuvien.js"></script>
    @RenderSection("head", false)
    <!-- menu jquery -->
    <link href="~/jQuery/Menu/style.css" rel="stylesheet" />


</head>
<body>
    <!--start content Page-->
    <section id="mainContainer">
        <header id="pageHeader">
            <img src="~/Images/LogoAdmin.jpg" />
            <div id="noiDungLogo">
                <h1>
                    PDA
                    <span>Shop</span>
                </h1>
            </div>
        </header>
        <nav id="wrapper" class="clear borderAL">
            <!-- -->
            <ul class="main_nav">
                <li>
                    <a href="@Url.Action("Index", "Home", new { area=""})">Trang chủ </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "PhanLoai", new { area="Admin"})">Phân loại </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "NhomSanPham", new { area="Admin"})">Nhóm sản phẩm </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "SanPham", new { area="Admin"})">Sản phẩm </a>
                </li>
                <li>
                    <a href="@Url.Action("DangXuat","KhachHang",new { area=""})">Đăng xuất</a>
                </li>
            </ul>

        </nav>

        <section id="mainContentAdmin">
            @* Ghi chú: nội dung thiết kế riêng của mỗi view *@
            @RenderBody()

        </section>
        <!--start Footer-->
        <footer id="ftr">
            <div id="footer">
                <p class="copyright">
                    &copy;&nbsp;&nbsp;2016 All Rights Reserved &nbsp;&bull;&nbsp; Design by
                    <a href="http://www.alphatek.edu.vn/">Diệp Anh - 13DTHC05</a>
                </p>
                <p class="link">
                    <a href="https://www.facebook.com/hoiyeuthichlaptrinh"><img src="~/images/facebook.png" /></a>
                    <a href="http://www.youtube.com/hoclaptrinh"><img src="~/images/youTube.png" /></a>
                </p>
            </div>
        </footer>
    </section>
</body>
</html>